version: "2.4"

services:
  webservice:
    container_name: webservice
    build: .
    ports:
    - 8081:8081
    environment:
      - OPAL_ELASTICSEARCH_URL=${OPAL_ELASTICSEARCH_URL}
      - OPAL_ELASTICSEARCH_PORT=${OPAL_ELASTICSEARCH_PORT}
      - ES_INDEX=${ES_INDEX}
      - SPARQL_ENDPOINT_PREVIOUS=${SPARQL_ENDPOINT_PREVIOUS}
      - SPARQL_ENDPOINT_LATEST=${SPARQL_ENDPOINT_LATEST}
      - GEO_URL_PREFIX=${GEO_URL_PREFIX}
      - GEO_REDIRECT=${GEO_REDIRECT}
    network_mode: "host"
