version: "2.4"

services:
  webservice:
    container_name: webservice
    build: .
    ports:
    - 8081:8081
    environment:
      - ES_INDEX=${ES_INDEX}
      - OPAL_ELASTICSEARCH_URL=${OPAL_ELASTICSEARCH_URL}
      - OPAL_ELASTICSEARCH_PORT=${OPAL_ELASTICSEARCH_PORT}
    network_mode: "host"
